### ISSUE TITLE
Error cannot use the Library

### ISSUE THREAD

**Issue by soumilshah1995** [kismetwireless/python-kismet-rest#4]
hello i have my kismet tool running on kali linux and i have downloaded your library using pip and when i run in py charm its giving me error 

/root/PycharmProjects/BlueSnarf/venv/bin/python /root/PycharmProjects/BlueSnarf/DosAlert.py
Traceback (most recent call last):
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 278, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: *KISMET: 0.0.0 1561387425 kali pcapdump,netxml,nettxt,gpsxml,alert 0 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 278, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('*KISMET: 0.0.0 1561387425 \x01kali\x01 \x01pcapdump,netxml,nettxt,gpsxml,alert\x01 0 \n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/PycharmProjects/BlueSnarf/DosAlert.py", line 5, in <module>
    for device in conn.device_summary():
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/kismet_rest/legacy.py", line 105, in device_summary
    return self.device_list(callback, cbargs)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/kismet_rest/legacy.py", line 127, in device_list
    return self.interact("GET", url, True, **kwargs)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/kismet_rest/base_interface.py", line 142, in interact
    response = self.session.get(full_url, stream=stream)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/root/PycharmProjects/BlueSnarf/venv/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('*KISMET: 0.0.0 1561387425 \x01kali\x01 \x01pcapdump,netxml,nettxt,gpsxml,alert\x01 0 \n'))

Process finished with exit code 1

**Comment by kismetwireless** [comment]
the kismet-rest library is only for modern versions of kismet which
implement the rest API; you're trying to talk to a non-http/non-rest very
old version of kismet.

You'll need the latest releases (2018, or preferably, 2019-05-2).
